### PR TITLE
Partially reverting #142

### PR DESCRIPTION
**Pull request by fniephaus**
See: https://github.com/GsDevKit/GsDevKit_todeClient/pull/6

### CODE REVIEW

**Comment by fniephaus** [comment]
I still don't understand why this is happening:
```
[96;1m   GsDevKit script: startClient travisClient_Pharo3.0 -t travisClient_Pharo3.0 -s travis -z /home/travis/build/hpi-swa/smalltalkCI/.smalltalk.ston[0m
[96;1m              path: /home/travis/smalltalkCI-master/_builds/GsDevKit_home/bin/startClient[0m
[96;1m=================[0m
[96;1m=================[0m
[96;1m   GsDevKit script: startClient -t travisClient_Pharo3.0 -s travis -z /home/travis/build/hpi-swa/smalltalkCI/.smalltalk.ston travisClient_Pharo3.0[0m
[96;1m              path: /home/travis/smalltalkCI-master/_builds/GsDevKit_home/dev/clients/travisClient_Pharo3.0/startClient[0m
[96;1m=================[0m
The requested client image: /home/travis/smalltalkCI-master/_builds/GsDevKit_home/dev/clients/travisClient_Pharo3.0/travisClient_Pharo3.0.image does not exist
Do you wish to create travisClient_Pharo3.0? [y/n]

No output has been received in the last 10 minutes, this potentially indicates a stalled build or something wrong with the build itself.

The build has been terminated
```
[Source](https://s3.amazonaws.com/archive.travis-ci.org/jobs/166269040/log.txt) [Build](https://travis-ci.org/hpi-swa/smalltalkCI/jobs/166269040)

It should be calling [save here](https://github.com/GsDevKit/GsDevKit_todeClient/blob/master/bin/createPharoTodeClient#L256) and then the file should exist, right?

**Comment by fniephaus** [comment]
Can you restart https://travis-ci.org/GsDevKit/GsDevKit_home/jobs/166276144 ?

**Comment by dalehenrich** [comment]
restarted...

**Comment by fniephaus** [comment]
Mh, now it failed in `tearDown`...try again please. Any ideas on https://github.com/GsDevKit/GsDevKit_home/pull/144#issuecomment-252513256?

**Comment by dalehenrich** [comment]
Without looking at all of the changes that you've made ... did you fiddle around with the way an image exits when test runs are finished ... presumably the original behavior was that the image always successfully saved the state of the image when the tests completed using the --save arg (I haven't read any code) to the image ...I recall you telling me that you are now using `exit <exit-code>` when finished with testing? And that would certainly foul up the scripts that I am using that are expecting to save the image using a new name when the tests finished ...

**Comment by fniephaus** [comment]
But this would affect all images, not just `Pharo-3`, right? AFAIK there's a weird issue with `--save` under Pharo-3. Why don't you use `mv` to rename the images and changes instead of [this](https://github.com/GsDevKit/GsDevKit_todeClient/blob/master/bin/createPharoTodeClient#L256)? Convenience?
Please restart the build once more. I currently have no understanding of what is actually happening  during this test and thus don't know why it is causing some weird problems (suite name not set).
Unfortunately, I need to get some rest now, so I'll need to work on this tomorrow again...

**Comment by fniephaus** [comment]
I just noticed this: [`--save` vs `save`](https://github.com/GsDevKit/GsDevKit_todeClient/blob/master/bin/createPharoTodeClient#L255-L256). Are you sure this is correct?

**Comment by dalehenrich** [comment]
On 10/9/16 3:55 PM, Fabio Niephaus wrote:
>
> But this would affect all images, not just |Pharo-3|, right? AFAIK 
> there's a weird issue with |--save| under Pharo-3. Why don't you use 
> |mv| to rename the images and changes instead of this 
> <https://github.com/GsDevKit/GsDevKit_todeClient/blob/master/bin/createPharoTodeClient#L256>? 
> Convenience?
>
It was working fine before ... did you our did you not change code in 
that area? I certainly haven't and it is possible that the Pharo folks 
have shipped a new version of the pharo3 vm and broken something, but at 
the moment I don't know whether or not that is true ...
>
> Please restart the build once more. I currently have no understanding 
> of what is actually happening during this test and thus don't know why 
> it is causing some weird problems (suite name not set).
> Unfortunately, I need to get some rest now, so I'll need to work on 
> this tomorrow again...
>
and I have no idea what you've changed in this area ... code shouldn't 
be pushed to master until all tests are passing ... making a/b tests 
possible ... I didn't sign up to spend a large chunk of my Sunday 
debugging this issue ...

Dale

**Comment by dalehenrich** [comment]
All I can say is that it was working fine before ... check out the 
hundreds of tests that have passed in the past ...

I do not know what changes you made in this area and the odds are it is 
something that you've changed ... I will ask for the third or fourth 
time ... did you add code to SmalltalkCI that causes the image to exit 
with an error code? Is it possible that that code is being invoked?

If you are certain that you've not changed anything in this area, then 
the next most likely culprit is the Pharo folks changing something ... 
my code has changed in this area for several months

Dale

**Comment by fniephaus** [comment]
The image has communicate the build status to Bash, since I've moved the entire result printing into the image. Loading should work fine. When tests are passing, smalltalkCI quits with zero, otherwise with a non-zero exit code. I'd say it would be more obvious if this actually impacts how your scripts work, especially [this one](https://github.com/GsDevKit/GsDevKit_todeClient/blob/master/bin/createPharoTodeClient#L255-L256) because it doesn't even use `test:`. Sorry for all the trouble, if I had known this before I would have tried to test it more with GsDevKit. Unfortunately, we don't have a staging area or something like this yet.

**Comment by fniephaus** [comment]
BTW, [Job #686.8](https://travis-ci.org/GsDevKit/GsDevKit_home/jobs/166276144) just passed. But for some reason, I don't see any output. Maybe a stdout redirection problem?

**Comment by dalehenrich** [comment]
Okay ... [here's the output from 4 months ago](https://travis-ci.org/GsDevKit/GsDevKit_home/jobs/138481688#L2695) ... the last time I changed GsDevKit_home code on the master branch ... presumably you've made changes to the way the code is executed ... in the past I believe that the test produced an xml file that the python script read and produced output ... I have noticed that the message `running suite: SmalltalkCI with: 37 tests` shows up right before the pretty output shows up in the ancient test run from 4 months ago and the most recent runs successful gemstone messages have this message showing up: `Running suite "GemStone-3.2.14 Server (travis)" with 40 tests.` and that little message appears to be missing from the smalltalkCI test run, so that might be a clue ...

**Comment by dalehenrich** [comment]
did you make changes to the gemstone run.sh code involved in running the test and producing the pretty output?

**Comment by fniephaus** [comment]
I did, but it wasn't much. [This one](https://github.com/hpi-swa/smalltalkCI/commit/a56eba0c2fe335b47041ae9667721b9bad0401f7) changed the exit code behavior and [here](https://github.com/hpi-swa/smalltalkCI/commits/master/gemstone/run.sh) is the overview list.

**Comment by dalehenrich** [comment]
What did you change in the Smalltalk code for GemStone to get the pretty print output --- specifically where did you make the change involving `Running suite "GemStone-3.2.14 Server (travis)"`? That's the bit that is not being run or the bit not being output ... I recall seeing commit comments about something involving remote gems and topaz, but I don't know where that was ... if the code is running as a gem, stdout is not necessarily dumped to the stdout of the calling process, since the gem is running in another os thread ... `topaz -l` on the other hand has stdout correctly routed ... did you make changes in this area along the way?

**Comment by dalehenrich** [comment]
... There is definitely a difference between the [smalltalkCI/run.sh code](https://github.com/hpi-swa/smalltalkCI/blob/f9cb651b4cc8a0e258fbd8702d1ad3a61b1e60a5/gemstone/run.sh#L264-L274) and the [GsDevKit_home/smalltalkCI script](https://github.com/GsDevKit/GsDevKit_home/blob/master/bin/smalltalkCI#L114-L119) ... the latter is running as a gem and stdout is lost ...

I think I can take care of those changes ... and I will merge this pull request, then fiddle with the script and we should be out of the woods!

**Comment by dalehenrich** [comment]
@fniephaus ... thanks for sticking with this and getting things back running cleanly!

**Comment by fniephaus** [comment]
Now worries, I promised to make sure we don't break GemStone support...and thanks for your help and your patience.

`Running suite "GemStone-3.2.14 Server (travis)` is printed because of [this](https://github.com/hpi-swa/smalltalkCI/blob/c02dbb767c27961d20b51a58ee9d44268c7a8e2d/gemstone/run.sh#L268), and it is printed from within the image (see [here](https://github.com/hpi-swa/smalltalkCI/blob/c02dbb767c27961d20b51a58ee9d44268c7a8e2d/repository/SmalltalkCI-Core.package/SCITestRunner.class/instance/setUp.st#L3)).
When smalltalkCI prints to `stdout`, it will use `SmalltalkCI platformClass stdout` and for GemStone this returns [`(Smalltalk at: #GsFile) stdoutServer`](https://github.com/hpi-swa/smalltalkCI/blob/c02dbb767c27961d20b51a58ee9d44268c7a8e2d/repository/SmalltalkCI-GemStone-Core.package/SmalltalkCIGemstone.class/class/stdout.st#L3). Everything seems to be working just fine when only the server is tested ([example](https://travis-ci.org/hpi-swa/smalltalkCI/jobs/166290391)). The `Pharo-3` client seems to have a weird saving problem and also, there is a problem with the Travis folds that I still need to solve. The folds need an unique identifier and currently they're not always unique which is why the Travis UI is broken. But this has nothing to do with the `Pharo-3` problem.

**Pull request merged**
