### PR TITLE
Use `loadRepository` instead of `loadRepositoryFor:`.

### PR DESCRIPTION
**Pull request by fniephaus**
`loadRepositoryFor:` is deprecated as of smalltalkCI [v2.5.0](https://github.com/hpi-swa/smalltalkCI/releases/tag/v2.5.0).

### CODE REVIEW

**Comment by dalehenrich** [comment]
One of the failures was due to an alpha download no longer available on our web-site ... running [this build](https://travis-ci.org/GsDevKit/GsDevKit_home/builds/299391147) on master branch as baseline for your run ...

**Comment by dalehenrich** [comment]
The Clients test and the SmalltalkCI tests were working fine a week ago (5 days ago) and it seems something outside of GsDevKit_home has broken ...

It's during the SmalltalkCI build and [the directory path seems to be broken in an odd way](https://travis-ci.org/GsDevKit/GsDevKit_home/jobs/299400193#L2853) in clients build (pharo-based) and [another mangled path for the SmalltalkCI build](https://travis-ci.org/GsDevKit/GsDevKit_home/jobs/299391155#L2906) ... 

The same [ approximate build ran fine 5 days ago](https://travis-ci.org/GsDevKit/GsDevKit_home/builds/296956454) ... so something fishy has changed in the last 5 days that affects Pharo and GemStone ...

**Comment by dalehenrich** [comment]
I see that the "symbolic link to project" is no longer created (4 days ago) ... I really don't have the time to debug this right now, but I hope that your changes haven't broken something that my guilds depend upon ...

**Comment by fniephaus** [comment]
Before removing the `git_cache` symlink, I searched for it in this repo and didn't find anything. After all, it hasn't been used by smalltalkCI for about a year now and I only left it for a while to not break things, but now people started relying on it which I want to avoid.
I might have opened this PR before merging all changes into `master`, so I'll run them again.
Maybe we also want to find a way to actually make use of semantic versioning which I've been using for smalltalkCI and lock versions when you make a GsDevKit release (if you do that).

**Comment by dalehenrich** [comment]
It's been awhile for me as well, but I have been relying on SmalltaCI for being able to build projects as well as test them and the two tests that started failing in the last 5 days are the ones that I've used to verify that the these projects are being built correctly ... at this point I don't have any clue what might be going on but the fact that both pharo and gemstone are impacted seems to point to SmalltalkCI as the failure ... the only other common denominator is GsDevKit_home and I always make sure the builds are green before merging into master ...

I don't know if semantic versions will solve this type of problem folks are expected to start using GsDevKit_home and then be able to update the projects they are using to the latest version of SmalltalkCI --- once they've install GsDevKit_home, I can't prevent them from using a particular version, yet the effect would be the same --- suddenly GsDevKit_home starts breaking ...

I don't really understand why you made the changes that you did nor do I know that that is the problem I am hitting, but I am curious what problem you are trying to solve ...

**Comment by fniephaus** [comment]
I was cleaning up things that were deprecated months ago, because I saw people starting to reply on them (e.g. the `git_cache` directory) last week.
Also, I've added support for custom script before/after loading/testing and I'm updating smalltalkCI's invocation. All of this should not affect GsDevKit as far as I can tell.
I think this PR should soon no longer be needed, but there will be some deprecation warnings that I will address with a slightly different PR.

**Comment by dalehenrich** [comment]
Hmmm, how am I able to use deprecated features without being aware that they are deprecated? 5 days ago I had green builds ... if the git-cache (or something else) is the real issue, I would want to have had build failures warning of the problem as soon as the feature was deprecated ... then I can change the .smalltalkCI to allow me to run with deprecated features, but then it would be **on me** when then the build breaks (for good) because the deprecated feature is removed ...

I really don't have time to fiddle with deprecated features right now ... but if I had had a warning, I would have been able to a) ask for more time before the deprecated feature is removed or b) fix the deprecation at my leisure months ago ...

What do you think? This isn't the first time that I've been bitten by deprecated features that I didn't know were deprecated ... and I think deprecation is valuable and important, but I would prefer to find out about deprecated features earlier rather than later:)

**Comment by fniephaus** [comment]
That's exactly what I've tried to address in the last couple of days with https://github.com/hpi-swa/smalltalkCI/commit/08359a033a49becddafeb3849152a507e6b32f91. If you use a deprecated method, there will be a red deprecation warning in the Travis log. After a couple of months, and when it's too much work to support a deprecated feature, the corresponding methods are removed with the next cleanup. As you may have noticed, I usually check GsDevKit when cleaning up, because I know it's depending on quite a lot of smalltalkCI internals.

**Comment by fniephaus** [comment]
Side note: Travis has had problems with their Mac infrastructure today and I'm still waiting for a couple of builds to run that I triggered this morning. Please bear with me, I'm working on fixing the smalltalkCI-related problem, but I also don't want to make things worse...

**Comment by dalehenrich** [comment]
I guess it depends upon where the banner shows up for deprecation warnings ... if I get a passed test I don't open the travis log ... sounds very good, then

**Comment by dalehenrich** [comment]
I appreciate your sensitivity towards GsDevKit_home ... I guess I was pushing the bounds of what is/was acceptable use of the"api" ..

**Comment by fniephaus** [comment]
Mh, well that's a tough one though. How is smalltalkCI supposed to inform you about things being deprecated in a passing build? I just hope you have to look at a few logs before I clean things up months later. Could you trigger a new build of GsDevKit to test if I was able to fix things?
There's this neat new short cut:
image

**Comment by fniephaus** [comment]
Whoops, please don't there's a problem with Pharo now that wasn't caught on `dev`...I'll keep you posted, but will have to fix this later tonight...

**Comment by dalehenrich** [comment]
whoops I just triggered the build ... I'll let it run to see what happens...

**Comment by dalehenrich** [comment]
if you use a SmalltalkCI deprecated feature and have not explicitly set *ignore deprecated failures* ( *ignore deprecated failures* could be the default --- I would always set if for GsDevKit_home) then smalltalkCI would treat a deprecated feature as a build failure and that would be the report ...

**Comment by fniephaus** [comment]
I've reverted the changes immediately, so it will break just like before.
That's a good idea, I'll add that as an option...

**Comment by dalehenrich** [comment]
I don't understand the "trigger build" feature ... it claims that it won't show up in history, so I don't know how to find it ... also when I triggered the build I got a message something like "problem loading data" ... and of course I've now moved off of that page in one of the 3 or 4 different web tabs that I've been using, so I don't know how to even find that error message ...

I always thought that restart build did the trick --- but apparently it doesn't ... which part isn't changed when you trigger a build ... is smalltalkCI part of the environment and does not get updated when you trigger the build?

**Comment by dalehenrich** [comment]
> I've reverted the changes immediately, so it will break just like before.

Is this a good thing or bad thing ... am I supposed to try again or wait for further instructions?

**Comment by dalehenrich** [comment]
I'm getting the following error:
```
ERROR 2318 , a UserDefinedError occurred (error 2318), reason:halt, Disk error: errno=20,ENOTDIR, Not a directory : /export/foos1/users/dhenrich/dev/_home/shared/repos/gs_port/metacello/.smalltalk.ston/repository for path: /export/foos1/users/dhenrich/dev/_home/shared/repos/gs_port/metacello/.smalltalk.ston/repository
```
when running:
```
./run.sh -s "GemStone-3.4.0" --gs-HOME=$GS_HOME /export/foos1/users/dhenrich/dev/_home/shared/repos/gs_port/metacello/.smalltalk.ston 
```
in a local SmalltalkCI checkout (hpi-swa/smalltalkCI@69f9192e1991d39c61155e573f4bb812ad5dea89) ... note that the the path is `/export/foos1/users/dhenrich/dev/_home/shared/repos/gs_port/metacello/.smalltalk.ston/repository` where the `.smalltalk-ston` file is somehow in the path ... 

I thought that this was the way we were supposed to run local builds ... and I assume that this used to work ... something is really fishy right now ..

**Comment by dalehenrich** [comment]
Here's the stack. SmalltalkCI is initiating the Metacello build, so I think SmalltalkCI is the source of the bad path:

```
ERROR 2318 , a UserDefinedError occurred (error 2318), reason:halt, Disk error: errno=20,ENOTDIR, Not a directory : /export/foos1/users/dhenrich/dev/_home/shared/repos/gs_port/metacello/.smalltalk.ston/repository for path: /export/foos1/users/dhenrich/dev/_home/shared/repos/gs_port/metacello/.smalltalk.ston/repository (UserDefinedError)
topaz > exec iferr 1 : stk 
==> 1 UserDefinedError (AbstractException) >> _signalWith: @6 line 25
2 UserDefinedError (AbstractException) >> signal @2 line 47
3 ServerFileDirectory (Object) >> error:        @6 line 7
4 ServerFileDirectory (FileDirectory) >> exists @14 line 7
5 MCFileTreeFileDirectoryUtils class >> directoryExists: @2 line 2
6 MCFileTreeRepository >> repositoryProperties  @7 line 5
7 MCFileTreeRepository >> directory:            @4 line 4
8 [] in MetacelloGemStonePlatform >> createRepository: @70 line 41
9 SmalltalkProxy >> at:ifPresent:               @11 line 7
10 MetacelloGemStonePlatform >> createRepository: @53 line 33
11 MetacelloMCBaselineProject (MetacelloMCProject) >> createRepository: @3 line 3
12 MetacelloRepositorySpec >> createRepository   @4 line 3
13 [] in MetacelloScriptEngine >> get            @28 line 11
14 OrderedCollection (Collection) >> do:         @6 line 10
15 [] in MetacelloScriptEngine >> get            @13 line 11
16 ExecBlock0 (ExecBlock) >> ensure:             @2 line 12
17 MetacelloProjectRegistration class >> copyRegistryRestoreOnErrorWhile: @9 line 14
18 MetacelloScriptEngine >> get                  @3 line 6
19 MetacelloScriptEngine (Object) >> perform:withArguments: @1 line 1
20 [] in MetacelloScriptExecutor >> execute:     @39 line 15
21 [] in MetacelloScriptApiExecutor >> executeString:do: @14 line 6
22 Array (Collection) >> do:                     @6 line 10
23 MetacelloScriptApiExecutor >> executeString:do: @7 line 4
24 String >> execute:against:                    @2 line 2
25 MetacelloScriptApiExecutor (MetacelloScriptExecutor) >> execute: @7 line 9
26 Metacello >> execute:args:                    @9 line 5
27 Metacello >> get                              @2 line 4
28 SCIGemStoneMetacelloLoadSpec (SCIMetacelloLoadSpec) >> basicLoadProjectOn: @19 line 11
29 SCIGemStoneMetacelloLoadSpec (SCIAbstractLoadSpec) >> loadProjectOn: @8 line 6
30 [] in SmalltalkCI >> load                     @20 line 10
31 Array (Collection) >> do:                     @6 line 10
32 [] in SmalltalkCI >> load                     @16 line 10
33 ExecBlock0 (ExecBlock) >> ensure:             @2 line 12
34 [] in SmalltalkCI >> load                     @9 line 11
35 [] in SmalltalkCI class >> fold:on:block:     @20 line 4
36 Time class >> secondsElapsedTime:             @6 line 11
37 Time class >> millisecondsElapsedTime:        @2 line 6
38 Time class >> millisecondsToRun:              @2 line 3
39 SmalltalkCI class >> timeToRun:               @2 line 3
40 SmalltalkCIGemstone class (SmalltalkCI class) >> fold:on:block: @6 line 4
41 SmalltalkCIGemstone class (SmalltalkCI class) >> fold:block: @3 line 2
42 SmalltalkCIGemstone class (SmalltalkCI class) >> stage:id:block: @5 line 4
43 SmalltalkCIGemstone (SmalltalkCI) >> load     @5 line 4
44 SmalltalkCI class >> load:projectDirectory:   @5 line 5
45 SmalltalkCI class >> load:                    @3 line 3
46 [] in Executed Code                           @11 line 7
47 [] in GsDeployer >> deploy:                   @22 line 8
48 ExecBlock0 (ExecBlock) >> on:do:              @3 line 44
49 [] in GsDeployer >> deploy:                   @8 line 9
50 [] in MCPlatformSupport class >> commitOnAlmostOutOfMemoryDuring: @12 line 7
51 ExecBlock0 (ExecBlock) >> ensure:             @2 line 12
52 MCPlatformSupport class >> commitOnAlmostOutOfMemoryDuring: @7 line 8
53 [] in GsDeployer >> mcPlatformSupportDo:      @14 line 11
54 ExecBlock0 (ExecBlock) >> ensure:             @2 line 12
55 GsDeployer >> mcPlatformSupportDo:            @10 line 12
56 GsDeployer >> deploy:                         @3 line 3
57 GsDeployer class >> bulkMigrate:              @5 line 15
58 Executed Code                                 @2 line 1
59 GsNMethod class >> _gsReturnToC               @1 line 1
```

**Comment by dalehenrich** [comment]
... or there is a bug with SmalltalkCI and GemStone 3.4.0 ... I found a few minutes while waiting for other operations to complete ... but my window just closed:(

**Comment by fniephaus** [comment]
Triggering a new build only adds a new entry on Travis CI and no commit. You could restart, but then you loose the time and logs.
If you could trigger a new build now (or restart an old one), things should be working again. BTW I'm already working on a #failOnDeprecationWarnings option.

**Comment by dalehenrich** [comment]
[restarted the two previously failing builds](https://travis-ci.org/GsDevKit/GsDevKit_home/builds/299457908) ... maybe it should be called #failOnSmalltalkCiDeprecationWarnings? ... I thought there was already a feature to fail on warnings ... that was intended to capture platform deprecation warnings --- for much the same reason:)

**Comment by fniephaus** [comment]
Thanks, the first one just passed! There's a `#failOn` option for `SCIMetacelloLoadSpec`s, the `#failOnDeprecationWarnings` would be in `SmalltalkCISpec->#testing`, but yes I guess I should rename that.

**Comment by fniephaus** [comment]
The [second build](https://travis-ci.org/GsDevKit/GsDevKit_home/jobs/299457916#L3692) failed and I don't quite know why yet, but I will figure that out...

**Comment by dalehenrich** [comment]
Nice to see progress and more greenity:) ... looks like the pharo 
variant is still failing and I see the deprecation warnings which is good...

If they are in different specs, it might not hurt to use a simpler name...

Dale

**Comment by fniephaus** [comment]
I've named it `#failOnSCIDeprecationWarnings`. Also, once the option is available, the warnings will be grouped at the bottom of the log, so you don't have too search for them :)
Still don't understand why `nil` is passed into that one method, but I'm restoring the original method now...

**Comment by dalehenrich** [comment]
... while you are in the middle of it, it is probably a good idea to include a pointer to the replace method for the deprecation ... frankly there are times where it easier for me to just edit the filetree method than it is to fire up a pharo image make the save and then write out the change:) so the more useful information in the travis log, the less often I have to setup a test environment

**Comment by fniephaus** [comment]
Found it, `GsDevKit_home` actually uses a very private API [here](https://github.com/GsDevKit/GsDevKit_home/blob/aa4b2219192f43e4762f0c0c84828c00178bf5bf/shared/repos/todeClient/GsDevKit-Structure.package/GsDevKitSharedReposGitRepository.class/instance/smalltalkCI.st#L5) and makes assumptions...

**Comment by dalehenrich** [comment]
don't recall why I did that, but presumably the "approved way" was not working for me ... that code was written 2 years ago, so perhaps things have become more flexible --- presumably the standard way was doing too much in terms of initialization

**Comment by fniephaus** [comment]
That's fine, but let's clean things up though. I think we should soon have a better deprecation process in place, so this shouldn't be a big problem :)

**Comment by dalehenrich** [comment]
do we expect the CLIENT build to pass now or is there additional work to be done?

**Comment by fniephaus** [comment]
I expect it to work now, sorry the Travis feedback loop was quite slow in the last couple of days.
Please try again :)

**Comment by dalehenrich** [comment]
no problem ... appreciate the effort and patience:) ... restarted

**Comment by fniephaus** [comment]
Ok, new (unexpected) error..I'll have a look at it tomorrow.

**Comment by dalehenrich** [comment]
thx

**Comment by fniephaus** [comment]
Mh, the only inst var I removed from `SmalltalkCISpec` was [`specName `](https://github.com/hpi-swa/smalltalkCI/commit/9eee91472a9f5da24bb61d56554e0952a7f5f8f6#diff-059b18e9c7771f55a2377b34fed4e99e) and I can't find any reference to that in this repo nor in `GsDevKit_todeClient` 🤔

**Comment by fniephaus** [comment]
Ok, there are [8 projects on Github](https://github.com/search?utf8=%E2%9C%93&q=specName+language%3ASton&type=Code) that use `#specName` (even though it is undocumented), one of which is `tode`. Inst var is restored, so please try again :)

**Comment by dalehenrich** [comment]
restarted ... I dimly recall that there is something important about being able to name the spec, but at the moment I don't recall the details, but apparently there is running code that uses it so it would seem to be useful ... is there a specific reason that you got rid of specName?

**Comment by fniephaus** [comment]
Ok, I just restored the side effect for Pharo as well. Please restart one more time...

**Comment by dalehenrich** [comment]
... restarted ...

**Comment by fniephaus** [comment]
ha, this time it's an unrelated "502 Bad Gateway" error :(

**Comment by dalehenrich** [comment]
restarted ...

**Comment by fniephaus** [comment]
All green again 😎

**Comment by dalehenrich** [comment]
now i'm ready to start failing due to deprecated api errors ...

**Comment by dalehenrich** [comment]
thanks for the effort ... it's much appreciated ...

**Comment by fniephaus** [comment]
For that, you need to set `#failOnSCIDeprecationWarnings : true` in your [config's `#testing`](https://github.com/hpi-swa/smalltalkCI#testcase-selection) section.
I hope to have some more time in December to send another PR which eliminates most of the deprecation warnings. I even made some design decision so that things are easier in GsDevKit_home and I hope I'll still have most of this in my head, so that'd make it easier for me to update your code :) At least everything is green for the time being...

**Comment by dalehenrich** [comment]
Excellent ... the improvements are worth the pain! Okay ... I will do that when my guns are aimed at GSDevKit_home ... for now I am fighting other battles, but it won't be too long before I visit GsDevKit_home with vengeance :)

**Pull request closed without merging**
