### PR TITLE
Fix installation steps [ci skip]

### PR DESCRIPTION
**Pull request by fniephaus**
Shouldn't there be pipes?

### CODE REVIEW

**Comment by dalehenrich** [comment]
Which problem are you trying to fix? Issue #97? Running the scripts on Windows?

At this point I've lost track of the thread --- and to't have time to track down right now -- the original script that was working fine on Ubuntu (and I think this script is the one that works on Ubuntu), then we changed the scripts to work on windows (in one spot maybe not both) and now they don't work on Linux ...

So I'm reluctant to change the samples until I know what problem you are attempting to solve:)

**Comment by fniephaus** [comment]
I'm not solving issue #97 here, it's a more obvious problem:
Running
`installServerClient 2>&1 tee $GS_HOME/install.log` doesn't work, a user needs to run
`installServerClient 2>&1 | tee $GS_HOME/install.log` instead, right?
Same should be true for all other install instructions.

**Comment by dalehenrich** [comment]
... and what os  are you running on?

**Comment by fniephaus** [comment]
Linux and OS X?

**Comment by dalehenrich** [comment]
That's a question not an answer .... you realize that I have had a number of ["fixes" to these scripts](https://github.com/fniephaus/GsDevKit_home/commits/patch-2/README.md) since I originally wrote the examples and apparently noone actually tests the script or ... the test results depends upon which version of bash they are running ...

If you look at the [diffs for the most recent change](https://github.com/fniephaus/GsDevKit_home/commit/5dd566ef7e7caf05cfb249423086f4048abe924a#diff-04c6e90faac2675aa89e2176d2eec7d8) you will see that someone complained about that form not working on osx (it may not work on windows either) ... and this is indeed about issue #97 --- because it is yet another alternative way of doing exactly this ...

**Comment by dalehenrich** [comment]
I have come to the conclusion that I will have to manually test and figure out this issue myself --- **when I have time** ---- because apparently there has been something wrong with every  solution that folks have given me and it seems that either they don't test the script or it only works on a limited set of bash versions ....

**Comment by dalehenrich** [comment]
Any future changes that I make in this area must be tested on a set of known versions of OSX, Linux and windows (Github Bash Shell).

**Comment by fniephaus** [comment]
Interesting, I obviously didn't know about this. I was able to achieve what I wanted to achieve and then I was trying to help, but apparently there is a lot more to this one...which you have to work on when you have time.

**Comment by dalehenrich** [comment]
I appreciate your attempt, but I have a broken script because I blindly accepted edits without testing them myself ... it works for me ... is not enough this time around ... and I wish I had the time to take care of all of the isseus in the world :)

**Comment by dalehenrich** [comment]
If you ahve the time to test this and document the versions of the oses and versions of bash that you've tested on it will save me time when I do attempt to fix this problem ...

**Comment by fniephaus** [comment]
If I had some time I'd be happy to help, but I'm also busy with other things 😢

**Comment by dalehenrich** [comment]
haha ... I know how that goes :)

**Pull request closed without merging**
